
[package]
name = "graphics_vulkano"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@capitalprawn.com>"]
edition = "2018"

[dependencies]
vulkano = "0.11.1"
vulkano-win = "0.11.1"
vulkano-shaders = "0.11.1"
winit = "0.18.1"
env_logger = "0.6.1"
log = "0.4.6"