[package]
name = "graphics_rendy"
version = "0.1.0"
authors = ["Fletcher Haynes <fletcher@capitalprawn.com>"]
edition = "2018"

[dependencies]
rendy = { git = "https://github.com/omni-viral/rendy", branch = "master" }